scroll-tech/frontends

src/pages/rollup/batch/index.tsx, src/views/blog/components/tableOfContents.tsx
---
- https://app.asana.com/0/0/1204184608175842
- https://app.asana.com/0/0/1204185091931127
=> fix: style when no tx hash

src/utils/ethereum.ts
[task](https://app.asana.com/0/1202293017617135/1204216063413714/f)
=> Support changing network on Brave

src/contexts/AppContextProvider.tsx, src/hooks/useTxHistory.ts, src/pages/bridge/Content.tsx, src/stores/txStore.ts
1. show bridge history error until people close it
2. show the whole error from backend
---
- https://app.asana.com/0/0/1202312026390285
=> fix: bridge history error

src/Homepage.tsx, src/views/blog/index.tsx
[task](https://app.asana.com/0/1202293017617135/1204225471430560/f)
=> Display footer under blog

src/pages/bridge/Content.tsx, src/pages/bridge/Send/useSendTransaction.ts, src/pages/bridge/components/TxTable/index.tsx, src/stores/txStore.ts
---
- https://app.asana.com/0/0/1204296239427634
- https://app.asana.com/0/0/1204296239427636
=> fix: better persist estimatedEndTime

package.json, src/components/LoadingPage/index.tsx, src/hooks/useBalance.tsx, src/hooks/useRollupInfo.ts, src/hooks/useSymbol.ts, src/hooks/useTokenInfo.ts, src/pages/ecosystem/Gallery/GalleryItem.tsx, src/pages/ecosystem/Gallery/index.tsx, src/views/blog/detail.tsx, yarn.lock
1. add loading indicator
2. deepened contour
3. bigger and farther link icons
---
- https://app.asana.com/0/0/1204367605288412
=> ecosystem improvements

src/pages/ecosystem/Header/index.tsx
---
- https://app.asana.com/0/0/1204449929137868
=> fix: ecosystem subtitle link

src/components/Footer/Subscribe.tsx, src/utils/common.ts
=> Frontends footer: Make newsletter button less dominant

src/components/Header/announcement.tsx
---
- https://app.asana.com/0/0/1204422365293939
=> fix: remove blue banner on specific pages

src/components/Header/announcement.tsx, src/stores/bridgeStore.ts, src/stores/rollupStore.ts, src/stores/txStore.ts
---
- https://app.asana.com/0/0/1204523554759662
=> perf: remove warning

src/constants/index.ts, src/contexts/Web3ContextProvider.tsx, src/pages/bridge/Send/index.tsx, src/pages/home/index.tsx
=> Do not force connect

src/constants/ecosystem.ts, src/constants/index.ts, src/hooks/useIsMobile.ts, src/pages/ecosystem/Filter/index.tsx, src/pages/ecosystem/Gallery/GalleryItem.tsx, src/pages/ecosystem/Gallery/index.tsx, src/pages/ecosystem/Header/index.tsx, src/pages/ecosystem/index.tsx
---
- https://app.asana.com/0/0/1204368887911985
=> feat: category filter

src/pages/bridge/Send/useSendStyles.ts, src/pages/home/components/sectionTitle.tsx
---
- https://app.asana.com/0/0/1204571271756186
- https://app.asana.com/0/0/1204569207781470
=> fix: adjustment

src/constants/transaction.ts, src/hooks/useTxHistory.ts, src/hooks/useVersionCheck.tsx, src/pages/bridge/Header/TransactionHistory.tsx, src/pages/bridge/Send/index.tsx, src/pages/bridge/Send/useSendTransaction.ts, src/pages/bridge/components/TxTable/StatusChip.tsx, src/pages/bridge/components/TxTable/index.tsx, src/stores/txStore.ts, src/utils/common.ts, src/utils/storageKey.ts
1. canceled and failed transactions will be removed when request list again and the error detail will error details will be reported to sentry and tagged as debug level (we can filter these errors precisely and check them)
2. accelerated transactions will replace old ones.
3. timeout for transactions that are not on chain is one hour, then they will be marked failed.
---
- https://app.asana.com/0/0/1204430995804454
- https://app.asana.com/0/0/1204546038752829
- https://app.asana.com/0/0/1204359404412671
- https://app.asana.com/0/0/1204368887911972
=> feat (bridge): failed && canceled tx

src/assets/blog/architecture.md, src/assets/blog/technicalPrinciples.md, src/assets/blog/upgradingPreAlphaTestnet.md, src/assets/blog/zkEVM.md
- fix: old URLs in blog articles
=> fix: old URLs in blog articles

src/pages/rollup/batch/index.tsx, src/pages/rollup/block/index.tsx, src/pages/rollup/chunk/index.tsx
=> fix: Robot Flex for rollupscan detail page

src/pages/new-bridge/hooks/useGasFee.ts
[we don't support EIP-1559](https://scrollco.slack.com/archives/C05M5U5HST0/p1693815901892659?thread_ts=1693815555.357449&cid=C05M5U5HST0)
=> fix: use gasPrice for L2

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/PULL_REQUEST_TEMPLATE.md
---
- https://app.asana.com/0/0/1204589186091402
=> docs: docs, issue/pr templates for open-source contribution

src/hooks/useBlockNumbers.ts, src/pages/new-bridge/components/TxTable/index.tsx, src/pages/new-bridge/hooks/useSendTransaction.ts, src/stores/claimStore.ts, src/stores/txStore.ts
1. https://scrollco.slack.com/archives/C0371RKQBNY/p1696055163786989?thread_ts=1696021363.424369&cid=C0371RKQBNY
2. avoid vertical screen shake (caused by line wrap)
3. reduce invalid usage of local storage
=> fix: use finalized instead of safe

src/components/Header/constants.ts, src/components/Header/desktop_header.tsx, src/components/Header/index.tsx
1. keep the root menu of the current menu item highlighted
2. keep the arrow pointing down during the drop-down menu opening rather than only when hovering the root menu
=> optimize: highlight root menu

src/pages/ecosystem/Gallery/GalleryItem.tsx, src/pages/ecosystem/Gallery/NetworkLabel.tsx, src/pages/ecosystem/Gallery/index.tsx
https://scrollco.slack.com/archives/C05RNSF0QAG/p1696611452561439
=> fix: add network label
